version: "3"
services:
  db:
    image: postgres:14.2-alpine
    restart: unless-stopped
    volumes:
      - db:/data
    ports:
      - 5432:5432
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=mix_test_bug_test"
      - "PGDATA=/data"

volumes:
  db:
